[package]
name = "zune-qoi"
version = "0.5.0-rc0"
authors = ["caleb <etemesicaleb@gmail.com>"]
edition = "2021"
repository = "https://github.com/etemesi254/zune-image/tree/dev/crates/zune-qoi"
license = "MIT OR Apache-2.0 OR Zlib"
keywords = ["qoi", "qoi-decoder", "decoder", "qoi-encoder", "encoder"]
categories = ["multimedia::images"]
exclude = ["fuzz/*"]
description = "Quite Ok Image (QOI) decoder and encoder part of the zune-image family"


[features]
log = ["zune-core/log"]
std = ["zune-core/std"]
default = ["std", "log"]
[dependencies]
zune-core = { path = "../zune-core", version = "^0.5.0-rc0" }

