[build-system]
requires = ["maturin>=1.3,<2.0"]
build-backend = "maturin"

[project]
name = "zune-image"
version = "0.4.0"
description = "The zune-image rust library python bindings"
license = "MIT"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
dependencies=["numpy>=1.16"]

[tool.maturin]
features = ["pyo3/extension-module"]
