name: Fuzz Deflate

on:
  push:
    branches: [ "main","dev" ]
    paths:
      - 'crates/zune-inflate/**'
  pull_request:
    branches: [ "main" ,"dev" ]
    paths:
      - 'crates/zune-inflate/**'
  schedule:
    - cron: '0 0 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Install
      run: cargo install cargo-fuzz
    - name: Fuzz deflate
      run: cargo +nightly fuzz run --fuzz-dir crates/zune-inflate/fuzz roundtrip fuzz-corpus/inflate -j2 -- -timeout=10s -max_total_time=120
    - name: Fuzz zlib
      run: cargo +nightly fuzz run --fuzz-dir crates/zune-inflate/fuzz roundtrip_zlib fuzz-corpus/inflate -j2 -- -timeout=10s -max_total_time=120
    - name: Normal Fuzz testing.
      run: cargo +nightly fuzz run --fuzz-dir crates/zune-inflate/fuzz decode_buffer fuzz-corpus/inflate -j2 -- -timeout=10s -max_total_time=120
