name: Semver checks

on:
  push:
    branches: [ "main","dev" ]
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches: [ "main" ,"dev" ]


jobs:
  semver-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install Cargo semver
        run: cargo install cargo-semver-checks --locked
      - name: Check semver
        run: cargo semver-checks --workspace

